FROM registry.access.redhat.com/ubi9/go-toolset:1.20 AS build

COPY . .

RUN go build api/cmd/api/main.go 

FROM ubi8/ubi-micro
COPY --from=build /opt/app-root/src/main go-autopro-api
CMD ./go-autopro-api