server:
  port: 8080
  host: 0.0.0.0

redis:
  address: "redis-7:6379"
  password: "changeme"

grpc:
  backend_service_address: "backend-service:50051"

logging:
  level: "info"
  format: "json"

clusters:
 - "lan-lab-001"
 - "lan-lab-002"